apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret
type: Opaque
stringData:
  DB_USER: admin
  DB_PASSWORD: admin123
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: changeMe