apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "memcached.fullname" . }}
  labels:
    {{- include "memcached.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "memcached.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "memcached.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{ toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: memcached
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.port }}
              name: memcached
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
