apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "memcached.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "memcached.name" . }}
  policyTypes:
  - Ingress
