apiVersion: v1
kind: Service
metadata:
  name: {{ include "memcached.fullname" . }}
spec:
  selector:
    app: {{ include "memcached.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 11211
