apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rabbitmq.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "rabbitmq.name" . }}
  policyTypes: [Ingress]
