apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
spec:
  selector:
    app: {{ include "rabbitmq.name" . }}
  ports:
  - name: amqp
    port: {{ .Values.service.amqpPort }}
  - name: management
    port: {{ .Values.service.managementPort }}
